import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';
const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4173'],{stdio:'inherit'});
let browser;
try{
 for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:4173/lab-assets/')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});let requests=0;const sessions=[],runs=[],results=[];const doc={id:'doc-001',name:'requirements.txt',format:'txt',category:'text',topic:'technical',version:1,passages:1,embedding_model:null,warnings:[],classification:'deterministic',source_bytes:40,section_count:1,indexing_seconds:0,imported_at:'2026-10-06'};const cases=[{id:'case-001',title:'Ordered list',suite:'Rendering',input:'List three colors',setup:[],attachment_ids:[],library_document_ids:[],assertions:[{kind:'contains',value:'Red'}],expected:'Three colors',timeout:30,tags:['rendering'],intent:'fresh'}];
 await page.route('**/api/v1/**',async route=>{const request=route.request(),path=new URL(request.url()).pathname.replace('/api/v1',''),method=request.method(),body=request.postDataJSON?.();let data={};
 if(path==='/status')data={backend:'ready',model:'Test local model',model_ready:true,router:'laya',router_ready:true,generating:false,context_size:4096,version:'test',vision_enabled:false};
 else if(path==='/profile')data={name:'',background:'',preferences:''};else if(path==='/identity')data={name:'Keno',personality:'Concise',response_examples:''};else if(path==='/tools/settings')data={automatic_memory:true,weather_enabled:false,search_enabled:false};else if(path==='/memories')data=[];
 else if(path==='/library/status')data={ready:true,configured:true,detail:null,formats:['.txt','.pdf'],encryption:'AES-256-GCM',manual_unlock:false};
 else if(path==='/library/documents')data=method==='POST'?doc:[doc];
 else if(path.includes('/library/documents/')&&path.includes('/passages/'))data={text:'Deadline: April 2027.',locator:'text block 1',name:doc.name};
 else if(path==='/library/search')data={mode:'keyword',excerpts:[{document_id:doc.id,name:doc.name,index:0,source_id:'S1',text:'Deadline: April 2027.',locator:'text block 1',rank:1,keyword_matches:1,cosine_similarity:null,fusion_score:0.0164}],coverage:[]};
 else if(path==='/conversations'&&method==='POST'){data={id:crypto.randomUUID(),title:body.title,created_at:new Date().toISOString(),turns:[]};sessions.unshift(data);}else if(path==='/conversations')data=sessions;
 else if(path.endsWith('/attachments'))data=[];else if(path.startsWith('/conversations/')){data=sessions.find(s=>s.id===path.split('/')[2])||{turns:[]};}
 else if(path==='/lab/runs')data={total:runs.length,items:runs};else if(path==='/lab/results'&&method==='GET')data={total:results.length,items:results};else if(path==='/lab/results'){data={id:crypto.randomUUID()};results.unshift({...body,...data,created_at:new Date().toISOString(),case:cases.find(c=>c.id===body.case_id),configuration:{model:'Test local model'},run:runs.find(r=>r.request_id===body.request_id)});}else if(path==='/lab/cases')data=cases;else if(path==='/lab/config')data={model:'Test local model',max_concurrency:1};else if(path==='/lab/snapshots')data={id:'snapshot-001',configuration:{model:'Test local model'}};
 else if(path==='/chat'){requests++;const context={route:{seconds:0,thinking:false,tool_family:'none',decisions:{thinking:{choice:'quick',confidence:0.9}}},first_token_seconds:0,total_seconds:0.4,prompt_tokens:150,tool_seconds:0,generated_tokens:null,document_sources:[{attachment_id:'lib:'+doc.id,library_document_id:doc.id,name:doc.name,page:null,chunk:1}],citation_check:{status:'missing'},history_turns:1};const reply='1. Red\n\n1. Blue\n   - Deep\n   - Light\n\n1. Green';const run={request_id:body.request_id,conversation_id:body.conversation_id,user_text:body.message,assistant_text:reply,status:'complete',created_at:new Date().toISOString(),metadata:JSON.stringify(context),context};runs.unshift(run);sessions.find(s=>s.id===body.conversation_id)?.turns.push(run);return route.fulfill({contentType:'text/event-stream',body:`event: context\ndata: ${JSON.stringify(context)}\n\nevent: delta\ndata: ${JSON.stringify({text:reply})}\n\nevent: done\ndata: ${JSON.stringify({request_id:body.request_id,conversation_id:body.conversation_id,reply,context})}\n\n`});}
 return route.fulfill({contentType:'application/json',body:JSON.stringify(data)});});
 await page.goto('http://127.0.0.1:4173/lab-assets/#/playground');await page.getByText('Local greeting · no model request').waitFor();assert.equal(requests,0);assert.equal(await page.locator('.topbar').count(),0);await page.goto('http://127.0.0.1:4173/lab-assets/#/brain-synapsis');await page.getByRole('heading',{name:'Brain Synapsis'}).waitFor();assert.equal(await page.locator('.brain-region-card').count(),4);assert.equal(await page.locator('.brain-anatomy .brain-lobe').count(),4);assert.equal(await page.locator('.brain-anatomy .brain-shell').count(),1);await page.goto('http://127.0.0.1:4173/lab-assets/#/playground');
 await page.goto('http://127.0.0.1:4173/lab-assets/#/settings');await page.getByLabel('Server access key').fill('mock-server-access-key');await page.getByRole('button',{name:'Connect',exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='Disconnect'&&!b.disabled));
 await page.goto('http://127.0.0.1:4173/lab-assets/#/playground');assert.equal(await page.locator('.chat-surface').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(24, 24, 27)');assert.equal(await page.locator('.composer-box').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(39, 39, 42)');await page.getByLabel('Message Keno').fill('List three colors');await page.getByRole('button',{name:'Send',exact:true}).click();await page.locator('.message-metrics').filter({hasText:'0.00s'}).waitFor();assert.equal(requests,1);assert.equal(await page.locator('.markdown ol > li').count(),3);assert.equal(await page.locator('.markdown ol li ul li').count(),2);assert.equal(await page.locator('.markdown ol').evaluate(el=>getComputedStyle(el).listStyleType),'decimal');
 await page.getByLabel('Message Keno').fill('Continue');await page.getByRole('button',{name:'Send',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.turn').length===2);assert.equal(runs[0].conversation_id,runs[1].conversation_id);
 await page.getByRole('button',{name:'Metrics',exact:true}).click();await page.getByText('generated_tokens',{exact:true}).waitFor();assert(await page.locator('.inspector').innerText().then(t=>t.includes('null')&&t.includes('0')));
 await mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/playground-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'requirements.txt',exact:true}).first().click();await page.getByText('Deadline: April 2027.',{exact:true}).waitFor();await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.goto('http://127.0.0.1:4173/lab-assets/#/benchmarks');await page.getByLabel('Select Ordered list').check();await page.getByRole('button',{name:'Run selected',exact:true}).click();await page.getByText('Benchmark completed.').waitFor({timeout:15000});assert.equal(results.length,2);
 await page.goto('http://127.0.0.1:4173/lab-assets/#/documents');await page.getByPlaceholder('What should we look for?').fill('Deadline');await page.getByRole('button',{name:'Retrieve',exact:true}).click();await page.getByText('Deadline: April 2027.',{exact:true}).waitFor();
 const stored=await page.evaluate(()=>({...localStorage}));assert.equal(stored['keno.serverAccessKey'],'mock-server-access-key');assert(!JSON.stringify(stored).includes('Deadline'));
 await page.goto('http://127.0.0.1:4173/lab-assets/#/playground');await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/playground-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.reload();await page.getByLabel('Message Keno').waitFor();await page.waitForFunction(()=>!document.querySelector('textarea[aria-label="Message Keno"]')?.disabled);assert.equal(await page.evaluate(()=>localStorage.getItem('keno.serverAccessKey')),'mock-server-access-key');
 await page.goto('http://127.0.0.1:4173/lab-assets/#/settings');await page.getByRole('button',{name:'Disconnect & forget key',exact:true}).click();assert.equal(await page.evaluate(()=>localStorage.getItem('keno.serverAccessKey')),null);await page.reload();await page.getByText('Disconnected.').waitFor();
 console.log('Browser smoke passed: local greeting, persisted auth with explicit forget, real SSE protocol, session continuity, nested numbering, metrics, source preview, benchmark persistence, retrieval and mobile layout. Tests use explicit mocked API fixtures, not live inference.');
}finally{await browser?.close();server.kill();}
