import {BookOpenCheck,History,Play,Plus,Power,RotateCcw,Trash2,UploadCloud} from 'lucide-react';
import {Button,Card,Empty,Input,Modal,Popconfirm,Space,Tag,Typography,Upload} from '../../shared/ui';
import {useSkills} from './hooks/useSkills';

export default function SkillsPage(){
 const s=useSkills();
 return <div>
  <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><Typography.Title level={2} className="!mb-1">Skills</Typography.Title><Typography.Text type="secondary">Reusable user-authored workflows. Skills can only use Keno’s existing allowlisted tools.</Typography.Text></div><Button type="primary" icon={<Plus size={14}/>} onClick={s.create}>Import skill</Button></div>
  <Card title="Automatic skill recognition" className="!mb-4"><div className="flex flex-wrap gap-2"><Input aria-label="Test skill match" className="min-w-64 flex-1" value={s.matchQuery} onChange={e=>s.setMatchQuery(e.target.value)} placeholder="Try a phrase, e.g. research brief about local AI"/><Button icon={<Play size={14}/>} disabled={!s.connected||!s.matchQuery.trim()} onClick={()=>void s.testMatch()}>Test match</Button></div>{s.match&&<div className="mt-3 rounded-lg border border-zinc-800 bg-zinc-950/50 p-3 text-xs">{s.match.match?<><div className="font-semibold">{s.match.match.name} <Tag>{Math.round((s.match.match.score||0)*100)}%</Tag></div><div className="mt-1 text-zinc-500">{s.match.match.match_reason} · {s.match.seconds.toFixed(4)}s</div></>:<div className="text-zinc-500">No skill crossed the activation threshold. Top candidates: {s.match.candidates.map(v=>v.id+' '+Math.round(v.score*100)+'%').join(' · ')||'none'}</div>}</div>}</Card>
  {s.skills.length?<div className="grid gap-3 xl:grid-cols-2">{s.skills.map(skill=><Card key={skill.id} title={<div className="flex items-center gap-2"><BookOpenCheck size={15}/>{skill.name}</div>} extra={<Space><Tag>{skill.enabled?'enabled':'disabled'}</Tag><Tag>{skill.risk}</Tag><Tag>v{skill.version}</Tag></Space>}><Typography.Paragraph type="secondary">{skill.description}</Typography.Paragraph><div className="mb-3 flex flex-wrap gap-1">{skill.triggers.map(trigger=><Tag key={trigger}>{trigger}</Tag>)}</div><div className="mb-3 text-[10px] text-zinc-500">Tools: {skill.required_tools.length?skill.required_tools.join(', '):'none'} · Used {skill.use_count} times · Last used {skill.last_used_at?new Date(skill.last_used_at).toLocaleString():'never'}</div><div className="flex flex-wrap gap-2"><Button size="small" onClick={()=>s.edit(skill)}>Edit</Button><Button size="small" icon={<History size={12}/>} onClick={()=>void s.showHistory(skill)}>Versions</Button><Button size="small" icon={<Power size={12}/>} onClick={()=>void s.toggle(skill)}>{skill.enabled?'Disable':'Enable'}</Button><Popconfirm title="Delete this skill?" onConfirm={()=>void s.remove(skill)}><Button size="small" danger icon={<Trash2 size={12}/>}>Delete</Button></Popconfirm></div></Card>)}</div>:<Card><Empty description="No skills yet. Import a workflow.md file to teach Keno a reusable procedure."/></Card>}
  <Modal open={s.open} onCancel={()=>s.setOpen(false)} onOk={()=>void s.save()} title={s.editingId?'Edit skill':'Import skill'} okText={s.editingId?'Save new version':'Import skill'} confirmLoading={s.busy} width={760}><div className="mb-3 flex items-center justify-between gap-3"><Typography.Paragraph type="secondary" className="!mb-0">Use Markdown with optional front matter: name, description, triggers, requires, risk, enabled.</Typography.Paragraph><Upload accept=".md,.markdown,.txt" beforeUpload={(file:File)=>{void s.loadFile(file);return Upload.LIST_IGNORE;}}><Button icon={<UploadCloud size={13}/>}>Choose workflow.md</Button></Upload></div><Input.TextArea aria-label="Skill Markdown" value={s.markdown} onChange={e=>s.setMarkdown(e.target.value)} autoSize={{minRows:18,maxRows:28}} className="!font-mono !text-xs"/></Modal>
  <Modal open={s.historyOpen} onCancel={()=>s.setHistoryOpen(false)} title="Skill versions" footer={null} width={700}>{s.history.length?<div className="space-y-2">{s.history.map(item=><div key={item.version} className="flex items-start justify-between gap-3 rounded-lg border border-zinc-800 p-3"><div><div className="font-semibold">{item.name} · v{item.version}</div><div className="mt-1 text-xs text-zinc-500">{new Date(item.updated_at).toLocaleString()} · {item.required_tools.join(', ')||'no tools'}</div></div><Button size="small" icon={<RotateCcw size={12}/>} disabled={s.busy} onClick={()=>void s.restore(item.version)}>Restore</Button></div>)}</div>:<Empty description="No older versions yet"/>}</Modal>
 </div>;
}
