import React,{cloneElement,isValidElement,useEffect,useRef,useState,type CSSProperties,type ReactElement,type ReactNode} from 'react';
import {Check,ChevronDown,Loader2,X} from 'lucide-react';

export const cn=(...parts:Array<string|false|null|undefined>)=>parts.filter(Boolean).join(' ');

export function Button({children,className='',type='default',size='default',block,danger,loading,icon,href,target,...props}:any){
 const variant=type==='primary'?'bg-zinc-100 text-zinc-950 hover:bg-zinc-200':type==='link'?'border-transparent bg-transparent text-zinc-200 underline-offset-4 hover:underline':type==='text'?'border-transparent bg-transparent text-zinc-400 hover:bg-zinc-900 hover:text-zinc-100':danger?'border-red-900/70 text-red-300 hover:bg-red-950/50':'border-zinc-800 bg-zinc-950 text-zinc-200 hover:bg-zinc-900 hover:text-zinc-50';
 const dimensions=size==='small'?'h-7 px-2 text-[11px]':size==='large'?'h-10 px-4 text-sm':'h-8 px-3 text-xs';
 const cls=cn('inline-flex items-center justify-center gap-2 rounded-md border font-medium transition-colors disabled:pointer-events-none disabled:opacity-40 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-zinc-500',dimensions,variant,block&&'w-full',className);
 const content=<>{loading?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:icon}{children}</>;
 if(href)return <a className={cls} href={href} target={target} rel={target==='_blank'?'noopener noreferrer':undefined}>{content}</a>;
 return <button {...props} type={type==='button'||type==='submit'||type==='reset'?type:'button'} className={cls}>{content}</button>;
}
export function Card({children,title,extra,className='',styles,size}:any){return <div className={cn('rounded-lg border border-zinc-800 bg-zinc-900/60',className)}>{(title||extra)&&<div className={cn('flex min-h-10 items-center justify-between gap-3 border-b border-zinc-800 px-3',size==='small'?'py-2':'py-2.5')}><div className="text-xs font-semibold text-zinc-100">{title}</div>{extra}</div>}<div className={size==='small'?'p-3':'p-3.5'} style={styles?.body as CSSProperties}>{children}</div></div>;}
function BaseInput({className='',prefix,onPressEnter,...props}:any){const input=<input {...props} onKeyDown={(e:any)=>{props.onKeyDown?.(e);if(e.key==='Enter')onPressEnter?.(e);}} className={cn('h-8 w-full rounded-md border border-zinc-800 bg-zinc-950 px-2.5 text-xs text-zinc-100 outline-none placeholder:text-zinc-600 focus:border-zinc-600 disabled:cursor-not-allowed disabled:opacity-50',prefix&&'pl-8',className)}/>;return prefix?<div className="relative"><span className="pointer-events-none absolute left-2.5 top-1/2 -translate-y-1/2 text-zinc-500">{prefix}</span>{input}</div>:input;}
function Password(props:any){const [show,setShow]=useState(false);return <div className="relative"><BaseInput {...props} type={show?'text':'password'} className={cn('pr-14',props.className)}/><button type="button" className="absolute right-2 top-1/2 -translate-y-1/2 text-[10px] text-zinc-500 hover:text-zinc-200" onClick={()=>setShow(v=>!v)}>{show?'Hide':'Show'}</button></div>;}
export function Textarea({className='',autoSize,...props}:any){return <textarea {...props} rows={autoSize?.minRows??props.rows??3} className={cn('w-full resize-y rounded-md border border-zinc-800 bg-zinc-950 px-2.5 py-2 text-xs leading-5 text-zinc-100 outline-none placeholder:text-zinc-600 focus:border-zinc-600 disabled:cursor-not-allowed disabled:opacity-50',className)}/>;}
export const Input=Object.assign(BaseInput,{Password,TextArea:Textarea});
export function Select({value,onChange,options=[],placeholder,disabled,className='',...props}:any){return <div className={cn('relative',className)}><select aria-label={props['aria-label']} disabled={disabled} value={value===undefined?'':String(value)} onChange={e=>{const raw=e.target.value;const match=options.find((o:any)=>String(o.value)===raw);onChange?.(match?match.value:raw);}} className="h-8 w-full appearance-none rounded-md border border-zinc-800 bg-zinc-950 px-2.5 pr-7 text-xs text-zinc-100 outline-none focus:border-zinc-600 disabled:opacity-50">{placeholder&&value===undefined&&<option value="">{placeholder}</option>}{options.map((o:any)=><option key={String(o.value)} value={String(o.value)} disabled={o.disabled}>{o.label}</option>)}</select><ChevronDown className="pointer-events-none absolute right-2 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-zinc-500"/></div>;}
export function Checkbox({checked,onChange,children,className='',disabled,...props}:any){return <label className={cn('inline-flex cursor-pointer items-center gap-2 text-xs text-zinc-300',disabled&&'cursor-not-allowed opacity-50',className)}><span className={cn('grid h-4 w-4 place-items-center rounded border',checked?'border-zinc-100 bg-zinc-100 text-zinc-950':'border-zinc-700 bg-zinc-950')}><input {...props} disabled={disabled} type="checkbox" checked={!!checked} onChange={onChange} className="sr-only"/>{checked&&<Check className="h-3 w-3"/>}</span>{children}</label>;}
export function Slider({min=0,max=100,step=1,value,onChange,className=''}:any){return <input className={cn('h-1.5 w-full accent-zinc-100',className)} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange?.(Number(e.target.value))}/>;}
export function InputNumber({value,onChange,min,max,disabled,className=''}:any){return <BaseInput className={className} type="number" min={min} max={max} disabled={disabled} value={value} onChange={(e:any)=>onChange?.(e.target.value===''?null:Number(e.target.value))}/>;}
export function Space({children,size=8,wrap,className=''}:any){const gap=Array.isArray(size)?size[0]:size;return <div className={cn('inline-flex items-center',wrap&&'flex-wrap',className)} style={{gap}}>{children}</div>;}
export function Tag({children,className=''}:any){return <span className={cn('inline-flex items-center rounded-md border border-zinc-800 bg-zinc-900 px-1.5 py-0.5 text-[10px] text-zinc-400',className)}>{children}</span>;}
export function Badge(props:any){return <Tag {...props}/>}
const titleClass:Record<number,string>={1:'text-3xl',2:'text-2xl',3:'text-xl',4:'text-base',5:'text-sm'};
function Title({level=1,children,className=''}:any){const TagName=(`h${level}`) as any;return <TagName className={cn('font-semibold tracking-tight text-zinc-50',titleClass[level]||'text-xl',className)}>{children}</TagName>;}
function Text({children,strong,type,className=''}:any){return <span className={cn('text-xs',type==='secondary'?'text-zinc-500':type==='danger'?'text-red-300':'text-zinc-200',strong&&'font-semibold text-zinc-100',className)}>{children}</span>;}
function Paragraph({children,type,className=''}:any){return <p className={cn('text-xs leading-5',type==='secondary'?'text-zinc-500':'text-zinc-300',className)}>{children}</p>;}
export const Typography={Title,Text,Paragraph};
export function Alert({type='info',message,description,closable,afterClose,className=''}:any){const [open,setOpen]=useState(true);if(!open)return null;return <div className={cn('relative rounded-lg border px-3 py-2 text-xs',type==='error'?'border-red-900/60 bg-red-950/30 text-red-200':type==='warning'?'border-amber-900/50 bg-amber-950/20 text-amber-200':type==='success'?'border-emerald-900/50 bg-emerald-950/20 text-emerald-200':'border-zinc-800 bg-zinc-900 text-zinc-200',className)}><div className="font-medium">{message}</div>{description&&<div className="mt-1 opacity-80">{description}</div>}{closable&&<button aria-label="Close" type="button" className="absolute right-2 top-2" onClick={()=>{setOpen(false);afterClose?.();}}><X className="h-3.5 w-3.5"/></button>}</div>;}
export function Empty({description='No data'}:any){return <div className="grid min-h-28 place-items-center text-xs text-zinc-600">{description}</div>;}
export function Statistic({title,value}:any){return <div><div className="text-[10px] text-zinc-500">{title}</div><div className="mt-1 text-xl font-medium text-zinc-100">{value}</div></div>;}
export function Progress({percent=0}:any){return <div className="h-1.5 overflow-hidden rounded-full bg-zinc-800"><div className="h-full rounded-full bg-zinc-200" style={{width:`${Math.max(0,Math.min(100,percent))}%`}}/></div>;}
export function Table({dataSource=[],columns=[],rowKey='key',className=''}:any){return <div className={cn('overflow-x-auto',className)}><table className="w-full border-collapse text-left text-xs"><thead><tr className="border-b border-zinc-800 text-zinc-500">{columns.map((col:any,i:number)=><th key={col.key||col.dataIndex||i} style={{width:col.width}} className="px-2.5 py-2 font-medium">{col.title}</th>)}</tr></thead><tbody>{dataSource.map((row:any,index:number)=><tr key={typeof rowKey==='function'?rowKey(row):row[rowKey]??index} className="border-b border-zinc-900 align-top hover:bg-zinc-900/50">{columns.map((col:any,i:number)=>{const value=col.dataIndex?row[col.dataIndex]:undefined;return <td key={col.key||col.dataIndex||i} className="px-2.5 py-2">{col.render?col.render(value,row,index):value as ReactNode}</td>;})}</tr>)}</tbody></table></div>;}
export function Descriptions({items=[],column=1}:any){return <dl className="grid gap-2" style={{gridTemplateColumns:`repeat(${column},minmax(0,1fr))`}}>{items.map((item:any)=><div key={item.key} className="rounded-md border border-zinc-800 p-2"><dt className="text-[10px] text-zinc-500">{item.label}</dt><dd className="mt-1 text-xs text-zinc-200">{item.children}</dd></div>)}</dl>;}
export function Collapse({items=[],className=''}:any){return <div className={cn('space-y-1',className)}>{items.map((item:any)=><details key={item.key} className="rounded-md border border-zinc-800/70 bg-zinc-950/40"><summary className="cursor-pointer list-none px-3 py-2 text-xs text-zinc-400">{item.label}</summary><div className="border-t border-zinc-800 px-3 py-2">{item.children}</div></details>)}</div>;}
export function Tabs({activeKey,onChange,items=[],className=''}:any){return <div className={className}><div className="flex gap-1 border-b border-zinc-800">{items.map((item:any)=><button key={item.key} type="button" onClick={()=>onChange?.(item.key)} className={cn('border-b-2 px-3 py-2 text-xs transition-colors',activeKey===item.key?'border-zinc-100 text-zinc-100':'border-transparent text-zinc-500 hover:text-zinc-200')}>{item.label}</button>)}</div><div>{items.find((item:any)=>item.key===activeKey)?.children}</div></div>;}
export function Modal({open,onCancel,onOk,title,children,footer,okText='OK',confirmLoading,width}:any){if(!open)return null;return <div className="fixed inset-0 z-[80] grid place-items-center bg-black/70 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)onCancel?.();}}><div className="max-h-[90vh] w-full overflow-y-auto rounded-xl border border-zinc-800 bg-zinc-900 shadow-2xl" style={{maxWidth:typeof width==='number'?width:width||640}}><div className="flex items-center justify-between border-b border-zinc-800 px-4 py-3"><div className="text-sm font-semibold">{title}</div><Button type="text" size="small" aria-label="Close" icon={<X className="h-4 w-4"/>} onClick={onCancel}/></div><div className="p-4">{children}</div>{footer!==null&&<div className="flex justify-end gap-2 border-t border-zinc-800 p-3"><Button onClick={onCancel}>Cancel</Button>{onOk&&<Button type="primary" loading={confirmLoading} onClick={onOk}>{okText}</Button>}</div>}</div></div>;}
export function Drawer({open,onClose,title,children,placement='right',width=420}:any){if(!open)return null;const left=placement==='left';return <div className="fixed inset-0 z-[75] bg-black/60" onMouseDown={e=>{if(e.target===e.currentTarget)onClose?.();}}><aside className={cn('absolute inset-y-0 border-zinc-800 bg-zinc-950 shadow-2xl',left?'left-0 border-r':'right-0 border-l')} style={{width:typeof width==='number'?width:width}}><div className="flex h-12 items-center justify-between border-b border-zinc-800 px-3"><strong className="text-xs">{title}</strong><Button type="text" size="small" aria-label="Close" icon={<X className="h-4 w-4"/>} onClick={onClose}/></div><div className="h-[calc(100%-3rem)] overflow-y-auto p-2">{children}</div></aside></div>;}
export function Popconfirm({title,onConfirm,children,disabled}:any){if(!isValidElement(children))return children;return cloneElement(children as ReactElement<any>,{onClick:(e:any)=>{(children as ReactElement<any>).props.onClick?.(e);if(!disabled&&window.confirm(String(title)))onConfirm?.();}});}
export function Tooltip({title,children}:any){return <span title={typeof title==='string'?title:undefined}>{children}</span>;}
export function Spin(){return <Loader2 className="h-5 w-5 animate-spin text-zinc-500"/>;}
export function Popover({content,children,placement}:any){const [open,setOpen]=useState(false),ref=useRef<HTMLDivElement>(null);useEffect(()=>{const close=(e:MouseEvent)=>{if(!ref.current?.contains(e.target as Node))setOpen(false);};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close);},[]);if(!isValidElement(children))return children;return <div ref={ref} className="relative inline-flex">{cloneElement(children as ReactElement<any>,{onClick:(e:any)=>{(children as ReactElement<any>).props.onClick?.(e);setOpen(v=>!v);}})}{open&&<div className={cn('absolute z-50 min-w-56 rounded-lg border border-zinc-800 bg-zinc-900 p-2 shadow-2xl',placement?.startsWith('top')?'bottom-full mb-2':'top-full mt-2',placement?.endsWith('Right')?'right-0':'left-0')}>{content}</div>}</div>;}
function UploadComponent({children,beforeUpload,accept,multiple,disabled}:any){return <label className={cn('inline-flex',disabled&&'pointer-events-none opacity-50')}><input className="sr-only" type="file" accept={accept} multiple={multiple} disabled={disabled} onChange={e=>{for(const file of Array.from(e.target.files||[]))beforeUpload?.(file);e.currentTarget.value='';}}/>{children}</label>;}
export const Upload=Object.assign(UploadComponent,{LIST_IGNORE:'__LIST_IGNORE__'});
export const Grid={useBreakpoint(){const [screens,setScreens]=useState({xl:typeof window!=='undefined'?window.innerWidth>=1280:false});useEffect(()=>{const update=()=>setScreens({xl:window.innerWidth>=1280});window.addEventListener('resize',update);return()=>window.removeEventListener('resize',update);},[]);return screens;}};
