import {useNavigate} from 'react-router-dom';
import {Alert,Button,Card,Checkbox,Descriptions,Empty,Input,Modal,Popconfirm,Select,Space,Table,Tag,Typography,Upload} from '../../shared/ui';
import {Download,FileText,History,MessageSquare,RefreshCcw,RotateCcw,Search,Trash2,Upload as UploadIcon,X} from 'lucide-react';
import {Json,Markdown,SourcePreview} from '../../components';
import {display,seconds} from '../../metrics.mjs';
import type {Doc,Source} from '../../shared/types';
import {useDocuments,type FolderItem} from './hooks/useDocuments';

const Field=({label,children}:{label:string;children:React.ReactNode})=><div className="space-y-1.5"><div className="text-[11px] text-zinc-400">{label}</div>{children}</div>;
const folderLabel=(item:FolderItem)=>'· '.repeat(Math.max(0,item.depth-1))+item.path+' · '+item.documents;

export default function DocumentsPage(){
 const d=useDocuments(),navigate=useNavigate();
 const columns=[
  {title:'Select',key:'select',width:72,render:(_:unknown,doc:Doc)=><Checkbox aria-label={'Select '+doc.name} checked={d.selected.includes(doc.id)} onChange={e=>d.setSelected(items=>e.target.checked?[...items,doc.id].slice(0,10):items.filter(id=>id!==doc.id))}/>},
  {title:'Document',dataIndex:'name',key:'name',render:(_:unknown,doc:Doc)=><div><Button type="link" className="!h-auto !p-0" onClick={()=>void d.openDetail(doc)}>{doc.name}</Button><div className="mt-1 text-[10px] text-zinc-500">{doc.format.toUpperCase()} · v{doc.version} · {doc.collection||'General'}{doc.folder?' · '+doc.folder:''} · {(doc.tags||[]).join(', ')||'no tags'}</div></div>},
  {title:'Classification',key:'classification',render:(_:unknown,doc:Doc)=><div>{doc.category}<div className="text-[10px] text-zinc-500">{doc.topic}</div></div>},
  {title:'Index',key:'index',render:(_:unknown,doc:Doc)=><div>{doc.passages} passages<div className="text-[10px] text-zinc-500">{doc.embedding_model?'Embedded':'Keyword only'} · encrypted</div></div>},
  {title:'Actions',key:'actions',width:190,render:(_:unknown,doc:Doc)=><Space size={4}><Button aria-label="Ask about document" icon={<MessageSquare size={14}/>} onClick={()=>navigate('/playground?doc='+doc.id)}/><Button aria-label="Download document" icon={<Download size={14}/>} onClick={()=>void d.download(doc)}/><Button aria-label="Re-index document" icon={<Search size={14}/>} disabled={d.busy} onClick={()=>void d.reindex(doc)}/><Popconfirm title={'Delete '+doc.name+' and its encrypted version history?'} onConfirm={()=>void d.remove(doc)}><Button danger aria-label="Delete document" icon={<Trash2 size={14}/>} disabled={d.busy}/></Popconfirm></Space>},
 ];
 return <div>
  <div className="mb-6 flex items-center justify-between gap-4"><div><Typography.Title level={2} className="!mb-1">Documents</Typography.Title><Typography.Text type="secondary">Encrypted originals, folder hierarchy, version history and local hybrid retrieval.</Typography.Text></div><Button icon={<RefreshCcw size={14}/>} onClick={()=>void d.refresh()} disabled={!d.connected||d.busy}>Refresh</Button></div>
  <Alert showIcon type={d.library?.ready?'success':'warning'} message={d.library?.ready?'Automatic encryption ready':'Document pipeline unavailable'} description={d.library?.detail||d.library?.encryption||'Connect to inspect configuration.'} className="!mb-4"/>
  <div className="grid gap-4 xl:grid-cols-[minmax(0,1.5fr)_minmax(340px,1fr)]">
   <div className="min-w-0 space-y-4">
    <Card title="Import document" extra={<Checkbox checked={d.embed} onChange={e=>d.setEmbed(e.target.checked)}>Build embeddings</Checkbox>}>
     <div className="mb-4 rounded-lg border border-zinc-800 bg-zinc-950/60 p-3"><Space><Upload showUploadList={false} beforeUpload={file=>{void d.upload(file as File);return Upload.LIST_IGNORE;}} accept={d.library?.formats?.join(',')} disabled={!d.connected||!d.library?.ready||d.busy}><Button type="primary" icon={<UploadIcon size={14}/>}>Choose file</Button></Upload><Typography.Text type="secondary">Files are encrypted before they are persisted.</Typography.Text></Space></div>
     <div className="grid gap-3 md:grid-cols-2"><Field label="Collection"><Input value={d.collection} onChange={e=>d.setCollection(e.target.value)} placeholder="General"/></Field><Field label="Folder"><Input value={d.folder} onChange={e=>d.setFolder(e.target.value)} placeholder="Projects/Keno"/></Field><Field label="Tags"><Input value={d.tags} onChange={e=>d.setTags(e.target.value)} placeholder="project, reference, notes"/></Field><Field label="Version action"><Select className="w-full" value={d.replace} onChange={d.setReplace} options={[{value:'',label:'Import as new document'},...d.docs.map(doc=>({value:doc.id,label:'Replace as next version · '+doc.name}))]}/></Field></div>
     <div className="mt-3 text-xs text-zinc-500">Folder paths support up to six levels. Replacing a document keeps encrypted historical versions.</div>{d.progress&&<div className="mt-2 text-xs text-zinc-400">{d.progress}</div>}
    </Card>
    <Card title="Library" extra={<Typography.Text type="secondary">{d.filteredDocs.length} / {d.docs.length} documents</Typography.Text>}><div className="mb-3 flex flex-wrap gap-2"><Input aria-label="Filter documents" className="min-w-52 flex-1" prefix={<Search size={13}/>} value={d.libraryQuery} onChange={e=>d.setLibraryQuery(e.target.value)} placeholder="Filter by name, folder, collection or tag…"/>{d.filteredDocs.length>0&&<Button onClick={()=>d.setSelected(d.filteredDocs.slice(0,10).map(doc=>doc.id))}>Select visible</Button>}{d.selected.length>0&&<><Button icon={<MessageSquare size={13}/>} onClick={()=>{const params=new URLSearchParams();d.selected.slice(0,4).forEach(id=>params.append('doc',id));navigate('/playground?'+params.toString());}}>Chat with selected</Button><Button type="text" icon={<X size={13}/>} onClick={()=>d.setSelected([])}>Clear</Button></>}</div><div className="mb-3 flex flex-wrap gap-2 text-[10px] text-zinc-500"><Tag>{d.collections.length} collections</Tag><Tag>{d.folders.length} folders</Tag><Tag>{d.docs.filter(doc=>!!doc.embedding_model).length} embedded</Tag><Tag>{d.selected.length} selected</Tag></div>{d.filteredDocs.length?<Table rowKey="id" dataSource={d.filteredDocs} columns={columns}/>:<Empty description={d.docs.length?'No documents match this filter':'No documents yet'}/>}</Card>
   </div>
   <Card title="Retrieval inspector" className="self-start">
    <Typography.Paragraph type="secondary">{d.selected.length?d.selected.length+' selected documents':'Search all imported documents'}</Typography.Paragraph>
    <Field label="Question or search phrase"><Input.TextArea value={d.question} onChange={e=>d.setQuestion(e.target.value)} placeholder="What should we look for?" maxLength={2000} autoSize={{minRows:4,maxRows:8}}/></Field>
    <div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2"><Field label="Collection"><Select className="w-full" value={d.selectedCollection} onChange={d.setSelectedCollection} options={[{value:'',label:'All collections'},...d.collections.map(item=>({value:item.name,label:item.name+' · '+item.documents}))]}/></Field><Field label="Folder"><Select className="w-full" value={d.selectedFolder} onChange={d.setSelectedFolder} options={[{value:'',label:'All folders'},...d.folders.map(item=>({value:item.path,label:folderLabel(item)}))]}/></Field><div className="md:col-span-2 xl:col-span-1 2xl:col-span-2"><Field label="Retrieval mode"><Select className="w-full" value={d.mode} onChange={d.setMode} options={[{value:'hybrid',label:'Semantic + keyword (auto fallback)'},{value:'keyword',label:'Keyword only'}]}/></Field></div></div>
    <div className="mt-3 flex justify-end gap-2"><Button icon={<Search size={14}/>} onClick={()=>void d.query()} disabled={!d.connected||d.busy||!d.question.trim()}>Retrieve</Button><Button type="primary" onClick={()=>void d.query(true)} disabled={!d.connected||d.busy||!d.question.trim()}>Ask</Button></div>
    {d.evidence&&<EvidenceView evidence={d.evidence} onSource={d.setSource}/>}
    {d.answer&&<AnswerView answer={d.answer} onSource={d.setSource}/>}
   </Card>
  </div>
  <Modal open={!!d.detail} title={d.detail?.name} onCancel={()=>d.setDetail(null)} footer={null} width={820}>
   {d.detail&&<><Descriptions size="small" column={3} items={[{key:'sections',label:'Sections',children:display(d.detail.section_count)},{key:'indexing',label:'Indexing time',children:seconds(d.detail.indexing_seconds)},{key:'versions',label:'Versions',children:d.versions.length||1}]}/><Typography.Paragraph type="secondary">{d.detail.classification}</Typography.Paragraph><Button icon={<FileText size={14}/>} onClick={()=>d.setSource({document_id:d.detail!.id,name:d.detail!.name,index:0})}>First passage</Button><Typography.Title level={5} className="!mt-5"><History size={14} className="mr-2 inline"/>Version history</Typography.Title><div className="space-y-2">{d.versions.map(version=><div key={version.version} className="flex items-center justify-between rounded-lg border border-zinc-800 p-3"><div><strong>v{version.version}{version.current?' · current':''}</strong><div className="text-[10px] text-zinc-500">{version.archived_at||version.imported_at||'Timestamp unavailable'} · {version.embedding_model?'embedded':'keyword only'}</div></div><Space><Button icon={<Download size={13}/>} onClick={()=>void d.download(d.detail!,version.version)}/>{!version.current&&<Popconfirm title={'Restore version '+version.version+' as a new current version?'} onConfirm={()=>void d.restoreVersion(d.detail!,version.version)}><Button icon={<RotateCcw size={13}/>} disabled={d.busy}>Restore</Button></Popconfirm>}</Space></div>)}</div><details className="mt-4"><summary className="cursor-pointer text-xs text-zinc-500">Document metadata</summary><Json value={d.detail}/></details></>}
  </Modal>
  {d.source&&<SourcePreview source={d.source} onClose={()=>d.setSource(null)}/>}
 </div>;
}

function EvidenceView({evidence,onSource}:{evidence:any;onSource:(source:Source)=>void}){return <div className="mt-5 space-y-3"><Typography.Text type="secondary">Mode: {evidence.mode}</Typography.Text>{evidence.retrieval&&<Space wrap className="!mt-2"><Tag>{seconds(evidence.retrieval.seconds)} retrieval</Tag><Tag>{Math.round(evidence.retrieval.match_strength*100)}% match</Tag><Tag>{evidence.retrieval.candidate_count} candidates</Tag><Tag>{evidence.retrieval.returned} returned</Tag></Space>}{evidence.excerpts.map((source:Source,index:number)=><Card size="small" key={index} className="!mt-2"><Button type="link" className="!h-auto !p-0" onClick={()=>onSource(source)}>[{source.source_id}] {source.name}</Button><div className="text-[10px] text-zinc-500">{source.locator}</div><Typography.Paragraph ellipsis={{rows:5,expandable:true}} className="!mt-2 !mb-0">{source.text}</Typography.Paragraph></Card>)}</div>;}
function AnswerView({answer,onSource}:{answer:any;onSource:(source:Source)=>void}){return <div className="mt-5"><Markdown text={answer.reply} sources={answer.sources} onSource={onSource}/><div className="mt-3 text-[10px] text-zinc-500">{seconds(answer.seconds)} total · {answer.citations_present?'Citation markers supplied':'No recognized citation markers'}{answer.truncated?' · output truncated':''}</div><Space wrap className="!mt-2">{answer.sources.map((source:Source,index:number)=><Button size="small" key={index} onClick={()=>onSource(source)}>[{source.source_id}] {source.name} · {source.locator}</Button>)}</Space></div>;}
