import {Button,Card,Empty,Space,Statistic,Table,Tag,Typography} from 'antd';
import {useNavigate} from 'react-router-dom';
import {ResponsiveContainer,LineChart,Line,CartesianGrid,XAxis,YAxis,Tooltip,BarChart,Bar} from 'recharts';
import {seconds} from '../../metrics.mjs';
import {useOverview} from './hooks/useOverview';

export default function HomePage(){
 const o=useOverview(),navigate=useNavigate(),runtime=o.status?.runtime as {quantization?:string;ram_available_bytes?:number;cpu_threads_available?:number}|undefined,cognitive=o.status?.cognitive as {stage?:string;detail?:string}|undefined;
 const generationAvg=o.generation.length?o.generation.reduce((a,b)=>a+b,0)/o.generation.length:null;
 const metrics=[['Model',o.status?.model||'Unavailable',runtime?.quantization||'Quantization unavailable'],['Average first token',seconds(o.firstAverage),'measured n='+o.firstMeasured.length],['Generation speed',generationAvg===null?'Unavailable':generationAvg.toFixed(1)+' tok/s',''],['Searches today',o.connected?String(o.searchesToday):'Unavailable',''],['Memories',o.memoryCount===null?'Unavailable':String(o.memoryCount),''],['Documents indexed',o.connected?String(o.docs.length):'Unavailable',''],['Brain Synapsis',cognitive?.stage||'idle',cognitive?.detail||'Waiting for activity'],['Recent failures',o.connected?String(o.failed.length):'Unavailable','in '+o.runs.length+' loaded requests']];
 return <div><div className="mb-6 flex items-center justify-between"><div><Typography.Title level={2} className="!mb-1">Home</Typography.Title><Typography.Text type="secondary">Live health, performance, activity and recent work.</Typography.Text></div><Button type="primary" onClick={()=>navigate('/playground')}>New chat</Button></div>
  <div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([title,value,note])=><Card key={title} size="small"><Statistic title={title} value={value}/>{note&&<div className="mt-1 text-[10px] text-zinc-500">{note}</div>}</Card>)}</div>
  <Card title="Service health" className="!mb-4"><div className="grid gap-3 sm:grid-cols-3 xl:grid-cols-6">{[['LLM',o.status?.model_ready],['Laya',o.status?.router_ready],['Lookup',o.status?.lookup_ready],['Search',o.status?.search_ready],['Embeddings',o.status?.embedding_ready],['Documents',o.connected]].map(([name,ready])=><div key={String(name)} className="rounded-lg border border-zinc-800 p-3"><div className="flex items-center gap-2"><span className={'h-2 w-2 rounded-full '+(ready?'bg-zinc-100':'bg-zinc-600')}/><strong>{String(name)}</strong></div><div className="mt-1 text-[10px] text-zinc-500">{ready?'Ready':'Unavailable'}</div></div>)}</div><div className="mt-3 text-xs text-zinc-500">CPU threads {runtime?.cpu_threads_available??'—'} · available RAM {runtime?.ram_available_bytes?Math.round(runtime.ram_available_bytes/1024/1024/1024*10)/10+' GB':'—'} · max context {o.status?.context_size??'—'}</div></Card>
  <div className="mb-4 grid gap-4 xl:grid-cols-2"><Card title="Latency trend">{o.trend.length?<ResponsiveContainer width="100%" height={220}><LineChart data={o.trend}><CartesianGrid stroke="#27272a" vertical={false}/><XAxis dataKey="run"/><YAxis/><Tooltip/><Line type="monotone" dataKey="first" name="First token" stroke="#fafafa" dot={false} isAnimationActive={false}/><Line type="monotone" dataKey="total" name="Total" stroke="#71717a" dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer>:<Empty description="No latency data"/>}</Card><Card title="Latest latency stages">{o.stages.length?<ResponsiveContainer width="100%" height={220}><BarChart layout="vertical" data={o.stages}><XAxis type="number"/><YAxis dataKey="stage" type="category" width={110}/><Tooltip/><Bar dataKey="seconds" fill="#fafafa" isAnimationActive={false}/></BarChart></ResponsiveContainer>:<Empty description="No recorded stage durations"/>}</Card></div>
  <div className="mb-4 grid gap-4 xl:grid-cols-2"><Card title="Recent conversations" extra={<Button type="link" onClick={()=>navigate('/playground')}>Open chat</Button>}>{o.sessions.length?<div className="space-y-1">{o.sessions.slice(0,6).map(session=><Button type="text" block className="!h-auto !justify-start !py-2" key={session.id} onClick={()=>navigate('/playground?session='+session.id)}><div className="text-left"><div>{session.title}</div><div className="text-[10px] text-zinc-500">{new Date(session.created_at).toLocaleString()}</div></div></Button>)}</div>:<Empty description="No conversations"/>}</Card><Card title="Recent runs" extra={<Button type="link" onClick={()=>navigate('/runs')}>View all</Button>}>{o.runs.length?<div className="space-y-2">{o.runs.slice(0,5).map(run=><Button key={run.request_id} block className="!h-auto !justify-between !py-2" onClick={()=>navigate('/runs?request='+encodeURIComponent(run.request_id))}><span className="truncate">{run.user_text}</span><Tag>{seconds(run.context.first_token_seconds)}</Tag></Button>)}</div>:<Empty description="No recorded requests"/>}</Card></div>
  <Card title="Per-model benchmark comparison" extra={<Button type="link" onClick={()=>navigate('/benchmarks')}>Run benchmark</Button>}><Table rowKey="model" pagination={false} dataSource={o.modelStats} columns={[{title:'Model',dataIndex:'model'},{title:'Recorded results',dataIndex:'runs'},{title:'Median first token',dataIndex:'first',render:value=>seconds(value)},{title:'Median total',dataIndex:'total',render:value=>seconds(value)},{title:'Pass',dataIndex:'pass'}]}/></Card>
 </div>;
}
