import {Button,Card,Empty,Input,Select,Space,Table,Tag,Typography} from '../../shared/ui';
import {Bookmark,Download,RotateCcw} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {Inspector,Markdown,SourcePreview,exportJson} from '../../components';
import {display} from '../../metrics.mjs';
import {useRuns} from './hooks/useRuns';
export default function RunsPage(){const r=useRuns(),navigate=useNavigate();const options=(values:string[])=>[{value:'',label:'All'},...values.map(value=>({value,label:value}))];return <div><div className="mb-6 flex items-center justify-between"><div><Typography.Title level={2} className="!mb-1">Runs</Typography.Title><Typography.Text type="secondary">Search recorded requests and inspect their evidence.</Typography.Text></div><Button icon={<Download size={14}/>} onClick={()=>exportJson('keno-runs.json',r.list)}>Export loaded</Button></div>
 <Card className="!mb-4"><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-5"><Input placeholder="Search input, response or request ID…" value={r.query} onChange={e=>r.setQuery(e.target.value)}/><Select value={r.status} onChange={r.setStatus} options={options(['complete','failed','running'])}/><Select value={r.session} onChange={r.setSession} options={[{value:'',label:'All sessions'},...r.sessions.map(s=>({value:s.id,label:s.title}))]}/><Select value={r.family} onChange={r.setFamily} options={options(['none','documents','memory','calculator','live','multiple'])}/><Select value={r.effort} onChange={r.setEffort} options={options([...new Set(r.runs.map(run=>String(run.context.route?.effort_policy||'')).filter(Boolean))])}/><Select value={r.documents} onChange={r.setDocuments} options={[{value:'',label:'Any document use'},{value:'yes',label:'With documents'},{value:'no',label:'Without documents'}]}/><Select value={r.thinking} onChange={r.setThinking} options={[{value:'',label:'Any thinking mode'},{value:'true',label:'Thinking enabled'},{value:'false',label:'Thinking disabled'}]}/><Input type="number" placeholder="First token ≥ seconds" value={r.latency} onChange={e=>r.setLatency(e.target.value)}/><Select value={r.model} onChange={r.setModel} options={[{value:'',label:'All recorded models'},...r.models.map(value=>({value,label:value}))]}/><Select value={r.suite} onChange={r.setSuite} options={[{value:'',label:'All suites'},...r.suites.map(value=>({value,label:value}))]}/><Input type="date" value={r.date} onChange={e=>r.setDate(e.target.value)}/></div><div className="mt-2 text-[10px] text-zinc-500">Filtering {r.runs.length} loaded of {r.runTotal} records.</div></Card>
 <div className="grid gap-4 xl:grid-cols-[minmax(300px,.7fr)_minmax(0,1.3fr)]"><Card>{r.list.length?<div className="space-y-2">{r.list.map(run=><Button block key={run.request_id} className="!h-auto !justify-between !py-3" onClick={()=>r.setSelected(run)}><span className="truncate text-left">{run.user_text}</span><Tag>{run.status}</Tag></Button>)}</div>:<Empty description="No matching runs"/>}</Card>{r.active&&<Card title={'Request '+r.active.request_id.slice(0,8)} extra={<Tag>{r.active.status}</Tag>}><Typography.Paragraph>{r.active.user_text}</Typography.Paragraph><Markdown text={r.active.assistant_text||'No confirmed saved response.'}/><Space wrap className="!my-4"><Button icon={<RotateCcw size={14}/>} onClick={()=>navigate('/playground?session='+r.active!.conversation_id+'&prompt_from='+r.active!.request_id)}>Retry as new run</Button><Button icon={<Bookmark size={14}/>} onClick={()=>void r.saveCase(r.active!)}>Save case</Button><Button onClick={()=>r.setCompare(r.active!)}>Set comparison</Button><Button icon={<Download size={14}/>} onClick={()=>exportJson('keno-run.json',r.active)}>Export</Button></Space>{r.compare&&r.compare.request_id!==r.active.request_id&&<Table pagination={false} size="small" dataSource={['first_token_seconds','total_seconds','context_prepare_seconds','tool_seconds','prompt_tokens'].map(key=>({key,previous:display(r.compare!.context[key]),current:display(r.active!.context[key])}))} columns={[{title:'Metric',dataIndex:'key'},{title:r.compare.request_id.slice(0,8),dataIndex:'previous'},{title:r.active.request_id.slice(0,8),dataIndex:'current'}]}/>}<div className="mt-4"><Inspector context={r.active.context} raw={r.active} onSource={r.setSource}/></div></Card>}</div>{r.source&&<SourcePreview source={r.source} onClose={()=>r.setSource(null)}/>}</div>;}
