import {useEffect,useState} from 'react';
import {Alert,Button,Card,Descriptions,Empty,Typography} from '../../shared/ui';
import {useLab} from '../../app/providers/LabProvider';
import {Json} from '../../components';
import {display} from '../../metrics.mjs';
import type {Diagnostics} from '../../shared/types';

const bytes=(value?:number)=>typeof value==='number'?(value/1024/1024/1024).toFixed(value>10*1024**3?1:2)+' GB':'—';
export default function RuntimePage(){
 const {status,library,config,connected,refresh,runs,api}=useLab(),[diagnostics,setDiagnostics]=useState<Diagnostics|null>(null),[diagError,setDiagError]=useState('');
 useEffect(()=>{if(!connected){setDiagnostics(null);return;}void api.get<Diagnostics>('/diagnostics').then(value=>{setDiagnostics(value);setDiagError('');}).catch(e=>setDiagError(e.message));},[connected,status?.generating]);
 const runtimeKeys=['backend','version','model','model_ready','router','router_ready','generating','context_size','vision_enabled'];
 const lowDisk=diagnostics?diagnostics.disk_free_bytes<2*1024**3:false;
 return <div><div className="mb-6 flex items-center justify-between"><div><Typography.Title level={2} className="!mb-1">Runtime</Typography.Title><Typography.Text type="secondary">Capabilities, recovery state and production diagnostics.</Typography.Text></div><Button onClick={()=>void refresh()} disabled={!connected}>Refresh</Button></div>
  {diagError&&<Alert type="warning" message="Diagnostics unavailable" description={diagError} className="!mb-4"/>}{lowDisk&&<Alert type="warning" message="Low disk space" description="Less than 2 GB is free. Model downloads, document imports and SQLite WAL growth may fail." className="!mb-4"/>}
  <div className="grid gap-4 xl:grid-cols-2"><Card title="Backend and model"><Descriptions column={1} size="small" items={runtimeKeys.map(key=>({key,label:key,children:<span className="font-mono">{display(status?.[key])}</span>}))}/><Typography.Title level={5}>Recovery guidance</Typography.Title><Typography.Paragraph type="secondary">{status?.model_ready?'LLM is ready.':'LLM is unavailable: check the llm container and active model.'} {status?.router_ready?'Laya is ready.':'Laya is unavailable: routing-dependent requests will fail.'}</Typography.Paragraph></Card><Card title="Document pipeline"><Descriptions column={1} size="small" items={[{key:'encryption',label:'Encryption configured',children:display(library?.configured)},{key:'ready',label:'Pipeline ready',children:display(library?.ready)},{key:'embedding',label:'Embedding implementation',children:'Xenova/multilingual-e5-small · optional local service'}]}/>{library?.detail&&<Typography.Text type="danger">{library.detail}</Typography.Text>}<div className="mt-4"><Json value={config}/></div></Card></div>
  <Card title="Production diagnostics" className="!mt-4">{diagnostics?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Descriptions column={1} items={[{key:'schema',label:'Schema',children:'v'+diagnostics.schema_version},{key:'integrity',label:'SQLite quick check',children:diagnostics.integrity}]}/><Descriptions column={1} items={[{key:'db',label:'Database',children:bytes(diagnostics.database_bytes)},{key:'wal',label:'WAL',children:bytes(diagnostics.wal_bytes)}]}/><Descriptions column={1} items={[{key:'free',label:'Disk free',children:bytes(diagnostics.disk_free_bytes)},{key:'uptime',label:'Backend uptime',children:Math.round(diagnostics.uptime_seconds/60)+' min'}]}/><Descriptions column={1} items={[{key:'skills',label:'Skills',children:String(diagnostics.counts.skills||0)},{key:'failed',label:'Failed turns',children:String(diagnostics.failed_turns)}]}/></div>:<Empty description="Diagnostics unavailable"/>}</Card>
  <Card title="Recent failed requests" className="!mt-4">{runs.filter(r=>r.status==='failed').length?<div className="space-y-2 font-mono text-xs">{runs.filter(r=>r.status==='failed').slice(0,10).map(run=><div key={run.request_id}>{run.created_at} · {run.request_id} · failed</div>)}</div>:<Empty description="No recent failures"/>}</Card>
 </div>;
}
