import {Button,Card,Checkbox,Empty,Input,Popconfirm,Select,Slider,Space,Tag,Typography} from '../../shared/ui';
import {History,Merge,RefreshCcw,Save,Search,Trash2} from 'lucide-react';
import {blankMemory,useMemory} from './hooks/useMemory';

const Field=({label,children}:{label:string;children:React.ReactNode})=><div className="space-y-1.5"><div className="text-[11px] text-zinc-400">{label}</div>{children}</div>;

export default function MemoryPage(){
 const m=useMemory();
 return <div>
  <div className="mb-6 flex items-center justify-between gap-4"><div><Typography.Title level={2} className="!mb-1">Memory</Typography.Title><Typography.Text type="secondary">Search, inspect, edit, merge and forget persistent memories.</Typography.Text></div><Space><Button icon={<Merge size={14}/>} onClick={()=>void m.findDuplicates()} disabled={!m.connected||m.busy}>Find duplicates</Button><Button icon={<RefreshCcw size={14}/>} onClick={()=>void m.load()} disabled={!m.connected||m.busy}>Refresh</Button></Space></div>
  <div className="grid gap-4 xl:grid-cols-2">
   <Card><div className="mb-4 flex gap-2"><Input aria-label="Search memories" value={m.query} onChange={e=>m.setQuery(e.target.value)} onPressEnter={()=>void m.load()} placeholder="Search memories…"/><Button icon={<Search size={14}/>} onClick={()=>void m.load()} disabled={!m.connected}>Search</Button></div>
    {m.items.length?<div className="space-y-3">{m.items.map(item=><Card size="small" key={item.key} title={<div><div className="font-mono">{item.key}</div><div className="text-[10px] font-normal text-zinc-500">{item.category}{item.pinned?' · pinned':''}</div></div>} extra={<Space size={4}><Button size="small" onClick={()=>void m.open(item)}>Edit</Button><Popconfirm title={'Forget '+item.key+'?'} onConfirm={()=>void m.remove(item.key)}><Button size="small" danger icon={<Trash2 size={13}/>} aria-label={'Forget '+item.key}/></Popconfirm></Space>}><Typography.Paragraph className="!mb-2">{item.content}</Typography.Paragraph><Space wrap size={[4,4]}><Tag>importance {item.importance.toFixed(2)}</Tag><Tag>confidence {item.confidence.toFixed(2)}</Tag><Tag>retrieved {item.retrieval_count||0}×</Tag><Tag>history {item.history_count||0}</Tag></Space>{item.last_reason&&<div className="mt-2 text-[10px] text-zinc-500">Last retrieval: {item.last_reason}</div>}</Card>)}</div>:<Empty description="No memories"/>}
   </Card>
   <div className="space-y-4">
    <Card title={m.edit.key?'Edit memory':'Add memory'}>
     <div className="space-y-4"><Field label="Key"><Input value={m.edit.key} maxLength={100} onChange={e=>m.setEdit({...m.edit,key:e.target.value})}/></Field><Field label="Content"><Input.TextArea value={m.edit.content} maxLength={1000} autoSize={{minRows:4,maxRows:10}} onChange={e=>m.setEdit({...m.edit,content:e.target.value})}/></Field><Field label="Category"><Select className="w-full" value={m.edit.category} onChange={value=>m.setEdit({...m.edit,category:value})} options={['profile','preference','project','fact','temporary'].map(value=>({value,label:value}))}/></Field><Field label={'Importance · '+m.edit.importance.toFixed(2)}><Slider min={0} max={1} step={.05} value={m.edit.importance} onChange={value=>m.setEdit({...m.edit,importance:Number(value)})}/></Field><Field label={'Confidence · '+m.edit.confidence.toFixed(2)}><Slider min={0} max={1} step={.05} value={m.edit.confidence} onChange={value=>m.setEdit({...m.edit,confidence:Number(value)})}/></Field><Checkbox checked={m.edit.pinned} onChange={e=>m.setEdit({...m.edit,pinned:e.target.checked})}>Pinned</Checkbox><Space><Button type="primary" icon={<Save size={14}/>} onClick={()=>void m.save()} disabled={!m.connected||m.busy||!m.edit.key||!m.edit.content}>Save</Button><Button onClick={m.clear}>Clear</Button></Space>{m.saved&&<div className="text-sm text-emerald-300">{m.saved}</div>}</div>
    </Card>
    {m.edit.key&&m.history.length>0&&<Card title={<span><History size={15} className="mr-2 inline"/>Correction history</span>}><Typography.Paragraph type="secondary">Older values stay local for auditability. Forgetting the memory clears this history too.</Typography.Paragraph><div className="space-y-2">{m.history.map(item=><div key={item.id} className="rounded-lg border border-zinc-800 p-3"><strong>{item.content}</strong><div className="mt-1 text-[10px] text-zinc-500">{item.replaced_at} · {item.reason} · confidence {item.confidence.toFixed(2)}</div></div>)}</div></Card>}
    {m.duplicates.length>0&&<Card title="Near-duplicates"><div className="space-y-3">{m.duplicates.map(item=><div key={item.keys.join('|')} className="rounded-lg border border-zinc-800 p-3"><strong>{Math.round(item.similarity*100)}% similar</strong><div className="mt-1 font-mono text-xs">{item.keys.join(' + ')}</div><div className="my-2 text-xs text-zinc-500">{item.preview.join(' / ')}</div><Button onClick={()=>void m.merge(item.keys)} disabled={m.busy}>Merge into {item.keys[0]}</Button></div>)}</div></Card>}
   </div>
  </div>
 </div>;
}
