import {useEffect,useState,type ReactNode} from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {X,ExternalLink,FileText} from 'lucide-react';
import {useLab} from './store';
import {display,seconds,stages,sanitize} from './metrics.mjs';
import type {Context,Source,Run} from './types';
export function Button({children,onClick,disabled=false,variant='',type='button',ariaLabel}:{children:ReactNode;onClick?:()=>void;disabled?:boolean;variant?:string;type?:'button'|'submit';ariaLabel?:string}){return <button type={type} aria-label={ariaLabel} className={'button '+variant} onClick={onClick} disabled={disabled}>{children}</button>;}
export function Empty({title,children}:{title:string;children?:ReactNode}){return <div className="empty"><FileText size={26}/><h2>{title}</h2><p>{children}</p></div>;}
export function Json({value}:{value:unknown}){return <pre className="json">{JSON.stringify(sanitize(value),null,2)}</pre>;}
export function Metric({label,value,note}:{label:string;value:ReactNode;note?:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>;}
export function Markdown({text,sources=[],onSource}:{text:string;sources?:Source[];onSource?:(s:Source)=>void}){
 const content=text.replace(/\[(S\d+)\](?!\()/g,(m,id)=>sources.some(s=>s.source_id===id)?`[${id}](#source-${id})`:m);
 return <div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{a:({href,children})=>{const source=href?.startsWith('#source-')?sources.find(s=>s.source_id===href.slice(8)):undefined;return source?<button className="citation" onClick={()=>onSource?.(source)}>{children}</button>:<a href={href} target="_blank" rel="noopener noreferrer">{children}</a>;},img:({alt})=><span className="muted">[Image: {alt||'external image disabled'}]</span>}}>{content}</ReactMarkdown></div>;
}
export function SourcePreview({source,onClose}:{source:Source;onClose:()=>void}){const {api}=useLab(),[text,setText]=useState<string|null>(source.text||null),[url,setUrl]=useState(''),[error,setError]=useState('');useEffect(()=>{const abort=new AbortController();let blobUrl='';const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();};window.addEventListener('keydown',escape);async function load(){if(source.text)return;const lib=source.library_document_id||source.document_id;const path=lib?(source.page?`/library/documents/${lib}/pages/${source.page}`:`/library/documents/${lib}/passages/${(source.index??((source.chunk||1)-1))+1}`):`/attachments/${source.attachment_id}/pages/${source.page||1}`;try{const r=await api.fetch(path,{signal:abort.signal});if(r.headers.get('content-type')?.includes('image/')){blobUrl=URL.createObjectURL(await r.blob());setUrl(blobUrl);}else{const d=await r.json();setText(d.text||JSON.stringify(d,null,2));}}catch(e){if(!abort.signal.aborted)setError((e as Error).message);}}void load();return()=>{abort.abort();window.removeEventListener('keydown',escape);if(blobUrl)URL.revokeObjectURL(blobUrl);};},[source,api]);return <div className="modal-backdrop" onClick={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label="Source preview" onClick={e=>e.stopPropagation()}><header><div><h2>{source.name}</h2><span className="muted">{source.locator|| (source.page?`Page ${source.page}`:'Extracted text')}</span></div><Button onClick={onClose}><X size={16}/><span>Close</span></Button></header>{error?<p className="error">{error}</p>:url?<img className="source-image" src={url} alt={source.name}/>:text?<pre className="source-text">{text}</pre>:<p>Loading local evidence…</p>}</section></div>;}
export function Sources({context,onSource}:{context:Context;onSource:(s:Source)=>void}){const list=[...(context.document_sources||[]),...(context.visual_sources||[])];const unique=list.filter((s,i)=>list.findIndex(other=>other.attachment_id===s.attachment_id&&other.page===s.page&&other.chunk===s.chunk)===i);const verify=context.web_verification as {verified_from?:number;conflict?:boolean;status?:string;cache_hit?:boolean}|undefined;return <div className="sources">{(verify?.verified_from||0)>=2&&<span className="source-verification">Verified from {verify?.verified_from} sources</span>}{verify?.conflict&&<span className="source-verification conflict">Sources conflict</span>}{verify?.cache_hit&&<span className="source-verification">Cached search</span>}{unique.map((s,i)=><button key={i} onClick={()=>onSource(s)}><FileText size={12}/>{s.name}{s.page?` · p.${s.page}`:s.locator?` · ${s.locator}`:''}</button>)}{context.web_sources?.map((s,i)=><a key={i} href={safeUrl(s.url)} target="_blank" rel="noopener noreferrer"><ExternalLink size={12}/>{s.title||s.url}</a>)}</div>;}
function safeUrl(url?:string){try{const u=new URL(url||'');return ['http:','https:'].includes(u.protocol)?u.href:undefined;}catch{return undefined;}}
export function Inspector({context,events=[],raw,browserSeconds,onSource}:{context:Context;events?:Array<{name:string;at:number;data:unknown}>;raw?:unknown;browserSeconds?:number;onSource:(s:Source)=>void}){const [tab,setTab]=useState('Pipeline'),route=context.route||{};return <section className="inspector"><div className="tab-strip">{['Pipeline','Decisions','Metrics','Sources','Raw'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>{tab==='Pipeline'&&<><p className="muted small">Observable events only. Server stage timestamps are unavailable. Durations below may overlap.</p><table><thead><tr><th>Stage</th><th>Duration</th></tr></thead><tbody>{stages(context).map(([label,duration,note])=><tr key={String(label)}><td>{String(label)}<small>{String(note)}</small></td><td className="mono">{seconds(duration)}</td></tr>)}</tbody></table>{events.length>0&&<details><summary>Browser event log · {events.length}</summary><Json value={events}/></details>}</>}{tab==='Decisions'&&<table><tbody>{Object.entries({...route,decisions:route.decisions||null}).map(([k,v])=><tr key={k}><td className="mono">{k}</td><td>{display(v)}</td></tr>)}</tbody></table>}{tab==='Metrics'&&<><table><tbody><tr><td>Browser observed duration</td><td>{seconds(browserSeconds)}</td></tr>{['first_token_seconds','total_seconds','context_prepare_seconds','prompt_eval_seconds','generation_seconds','model_total_seconds','model_first_delta_seconds','model_first_reasoning_seconds','hidden_reasoning_seconds','model_first_token_seconds','prompt_tokens','server_prompt_tokens','generated_tokens','prompt_tokens_per_second','generation_tokens_per_second','cache_usage','execution_mode','effective_max_tokens','history_turns','retrieved_history','context_policy','reply_language','thinking_budget','finish_reason'].map(k=><tr key={k}><td className="mono">{k}</td><td className="mono">{display(context[k])}</td></tr>)}</tbody></table><p className="muted small">Prompt evaluation, generation speed and cache usage are shown when llama.cpp reports them; otherwise bounded estimates are used. No hidden reasoning text is displayed.</p></>}{tab==='Sources'&&<><Sources context={context} onSource={onSource}/><Json value={{coverage:context.document_coverage_details,citation_check:context.citation_check,web_verification:context.web_verification}}/></>}{tab==='Raw'&&<Json value={raw??context}/>}</section>;}
export function exportJson(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(sanitize(data),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function RunSummary({run,onClick}:{run:Run;onClick:()=>void}){return <button className="run-row" onClick={onClick}><span className={'status-dot '+run.status}/><span><strong>{run.user_text.slice(0,85)}</strong><small>{run.session_title||run.conversation_id.slice(0,8)} · {new Date(run.created_at).toLocaleString()}</small></span><span className="mono">{seconds(run.context.first_token_seconds)}</span><span className="mono muted">{run.status}</span></button>;}
