import {useEffect,useState} from 'react';
import {Search,RefreshCcw,Merge,Trash2,Save,History} from 'lucide-react';
import {useLab} from './store';
import {Button,CheckField,Empty,SelectField,SliderField,TextArea,TextInput} from './components';

interface MemoryRow {key:string;content:string;category:string;pinned:boolean;importance:number;confidence:number;retrieval_count:number;last_reason:string;history_count?:number;updated_at?:string}
interface MemoryHistory {id:number;memory_key:string;content:string;category:string;importance:number;confidence:number;replaced_at:string;replacement_request_id?:string|null;reason:string}
const blank:MemoryRow={key:'',content:'',category:'fact',pinned:false,importance:.5,confidence:.8,retrieval_count:0,last_reason:'',history_count:0};

export default function Memory(){
 const {api,connected,setError}=useLab();
 const [query,setQuery]=useState(''),[items,setItems]=useState<MemoryRow[]>([]),[edit,setEdit]=useState<MemoryRow>(blank),[duplicates,setDuplicates]=useState<Array<{keys:string[];similarity:number;preview:string[]}>>([]),[history,setHistory]=useState<MemoryHistory[]>([]),[busy,setBusy]=useState(false),[saved,setSaved]=useState('');
 async function load(q=query){if(!connected)return;try{setItems(await api.get<MemoryRow[]>('/memories?q='+encodeURIComponent(q)));}catch(e){setError((e as Error).message);}}
 async function openMemory(memory:MemoryRow){setEdit({...memory});setSaved('');try{setHistory(await api.get<MemoryHistory[]>('/memory-history/'+encodeURIComponent(memory.key)));}catch(e){setHistory([]);setError((e as Error).message);}}
 useEffect(()=>{void load('');},[connected,api]);
 async function save(){if(!edit.key.trim()||!edit.content.trim())return;setBusy(true);try{const result=await api.put<MemoryRow&{superseded_previous?:boolean}>('/memories/'+encodeURIComponent(edit.key),{key:edit.key,content:edit.content,category:edit.category,pinned:edit.pinned,importance:edit.importance,confidence:edit.confidence,source_conversation_id:null,expires_at:null});setEdit(blank);setHistory([]);setSaved(result.superseded_previous?'Memory updated. Previous value preserved in correction history.':'Memory saved.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(key:string){if(!confirm('Forget '+key+'?'))return;setBusy(true);try{await api.remove('/memories/'+encodeURIComponent(key));if(edit.key===key){setEdit(blank);setHistory([]);}await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function findDuplicates(){setBusy(true);try{setDuplicates(await api.get('/memories/duplicates'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function merge(keys:string[]){setBusy(true);try{await api.post('/memories/merge',{keys,target_key:keys[0]});setDuplicates(old=>old.filter(d=>d.keys.join('|')!==keys.join('|')));await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="page-heading"><div><h1>Memory</h1><p>Search, inspect, edit, merge and forget persistent memories.</p></div><div className="actions"><Button onClick={()=>void findDuplicates()} disabled={!connected||busy}><Merge size={14}/>Find duplicates</Button><Button onClick={()=>void load()} disabled={!connected||busy}><RefreshCcw size={14}/>Refresh</Button></div></div>
 <div className="two-columns memory-page"><section className="panel"><div className="filters"><TextInput aria-label="Search memories" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load();}} placeholder="Search memories…"/><Button onClick={()=>void load()} disabled={!connected}><Search size={14}/>Search</Button></div>
 {!items.length?<Empty title="No memories">Saved facts and preferences will appear here.</Empty>:items.map(m=><article className="memory-card" key={m.key}><div className="section-heading"><div><strong className="mono">{m.key}</strong><small>{m.category}{m.pinned?' · pinned':''}</small></div><div className="actions"><Button onClick={()=>void openMemory(m)}>Edit</Button><Button ariaLabel={'Forget '+m.key} onClick={()=>void remove(m.key)}><Trash2 size={13}/></Button></div></div><p>{m.content}</p><div className="memory-meta"><span>importance {m.importance.toFixed(2)}</span><span>confidence {m.confidence.toFixed(2)}</span><span>retrieved {m.retrieval_count||0}×</span><span>history {m.history_count||0}</span></div>{m.last_reason&&<small className="muted">Last retrieval: {m.last_reason}</small>}</article>)}</section>
 <section><div className="panel settings-panel"><h2>{edit.key?'Edit memory':'Add memory'}</h2><label>Key<TextInput value={edit.key} maxLength={100} onChange={e=>setEdit({...edit,key:e.target.value})}/></label><label>Content<TextArea value={edit.content} maxLength={1000} onChange={e=>setEdit({...edit,content:e.target.value})}/></label><label>Category<SelectField value={edit.category} onChange={e=>setEdit({...edit,category:e.target.value})}>{['profile','preference','project','fact','temporary'].map(v=><option key={v}>{v}</option>)}</SelectField></label><label>Importance · {edit.importance.toFixed(2)}<SliderField min={0} max={1} step={.05} value={edit.importance} onChange={value=>setEdit({...edit,importance:Number(value)})}/></label><label>Confidence · {edit.confidence.toFixed(2)}<SliderField min={0} max={1} step={.05} value={edit.confidence} onChange={value=>setEdit({...edit,confidence:Number(value)})}/></label><CheckField checked={edit.pinned} onChange={e=>setEdit({...edit,pinned:e.target.checked})}>Pinned</CheckField><div className="actions"><Button variant="primary" onClick={()=>void save()} disabled={!connected||busy||!edit.key||!edit.content}><Save size={14}/>Save</Button><Button onClick={()=>{setEdit(blank);setHistory([]);}}>Clear</Button></div>{saved&&<p className="success">{saved}</p>}</div>
 {edit.key&&history.length>0&&<div className="panel memory-history"><h2><History size={15}/> Correction history</h2><p className="muted small">Older values stay local for auditability. Forgetting the memory clears this history too.</p>{history.map(item=><article key={item.id}><strong>{item.content}</strong><small>{item.replaced_at} · {item.reason} · confidence {item.confidence.toFixed(2)}</small></article>)}</div>}
 {duplicates.length>0&&<div className="panel"><h2>Near-duplicates</h2>{duplicates.map(d=><article className="duplicate-memory" key={d.keys.join('|')}><strong>{Math.round(d.similarity*100)}% similar</strong><p className="mono">{d.keys.join(' + ')}</p><small>{d.preview.join(' / ')}</small><Button onClick={()=>void merge(d.keys)} disabled={busy}>Merge into {d.keys[0]}</Button></article>)}</div>}</section></div></>;
}
