import {useEffect,useState} from 'react';
import {Download,RefreshCcw,ServerCog} from 'lucide-react';
import {useLab} from './store';
import {Button,Json} from './components';
import {preferences} from './preferences.mjs';

interface RuntimeModels {installed:Array<{name:string;bytes:number;quantization:string|null;loaded:boolean;managed:boolean}>;loaded:string;pending:string|null;recommendation:{threads:number;context_size:number;quantization:string;reason:string};activation:string}

export default function Settings({theme,setTheme}:{theme:string;setTheme:(s:string)=>void}){
 const {connected,api,connect,disconnect,library,status,refresh,setError}=useLab();
 const [key,setKey]=useState(''),[pending,setPending]=useState(false),[tab,setTab]=useState('Connection');
 const [profile,setProfile]=useState({name:'',background:'',preferences:''}),[identity,setIdentity]=useState({name:'Keno',personality:'',response_examples:''});
 const [tools,setTools]=useState({automatic_memory:true,weather_enabled:false,search_enabled:false}),[labPrefs,setLabPrefs]=useState(preferences),[saved,setSaved]=useState('');
 const [models,setModels]=useState<RuntimeModels|null>(null),[selectedModel,setSelectedModel]=useState(''),[modelUrl,setModelUrl]=useState(''),[modelFilename,setModelFilename]=useState(''),[modelBusy,setModelBusy]=useState(false);
 async function loadModels(){if(!connected)return;try{const data=await api.get<RuntimeModels>('/runtime/models');setModels(data);setSelectedModel(data.pending||data.loaded||data.installed[0]?.name||'');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{if(!connected)return;void Promise.all([api.get<typeof profile>('/profile'),api.get<typeof identity>('/identity'),api.get<typeof tools>('/tools/settings'),api.get<RuntimeModels>('/runtime/models')]).then(([p,i,t,m])=>{setProfile(p);setIdentity(i);setTools(t);setModels(m);setSelectedModel(m.pending||m.loaded||m.installed[0]?.name||'');}).catch(e=>setError(e.message));},[connected,api]);
 async function save(path:string,value:unknown){try{await api.put(path,value);setSaved('Saved on your server.');await refresh();}catch(e){setError((e as Error).message);}}
 async function stageModel(){if(!selectedModel)return;setModelBusy(true);try{const result=await api.put<{pending:string;restart_required:boolean;command:string}>('/runtime/model',{name:selectedModel});setSaved(result.restart_required?'Model staged. Recreate llm and backend to activate it.':'This model is already loaded.');await loadModels();}catch(e){setError((e as Error).message);}finally{setModelBusy(false);}}
 async function downloadModel(){if(!modelUrl.trim())return;setModelBusy(true);setSaved('Downloading model through the isolated egress service…');try{const result=await api.post<{name:string;bytes:number}>('/runtime/models/download',{url:modelUrl.trim(),filename:modelFilename.trim()||null});setSaved('Installed '+result.name+'. Select it below and stage it for activation.');setModelUrl('');setModelFilename('');await loadModels();}catch(e){setError((e as Error).message);setSaved('');}finally{setModelBusy(false);}}
 return <><div className="page-heading"><div><h1>Settings</h1><p>Connection, personalization, tools and local runtime management.</p></div></div>
 <div className="tab-strip settings-tabs">{['Connection','Personalization','Tools','Runtime','Lab'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);setSaved('');}}>{t}</button>)}</div>
 <section className="panel settings-panel">
 {tab==='Connection'&&<><h2>Backend access</h2><p className="muted">Same-origin FastAPI API. {connected?'Connected.':'Disconnected.'} After a successful connection, the access key is saved for this site and restored automatically after reload.</p><form onSubmit={e=>{e.preventDefault();setPending(true);void connect(key).then(()=>{setKey('');setSaved('Connected');}).catch(e=>setError(e.message)).finally(()=>setPending(false));}}><label>Server access key<input type="password" value={key} autoComplete="off" placeholder="Paste your server key" onChange={e=>setKey(e.target.value)}/></label><div className="actions"><Button type="submit" variant="primary" disabled={pending||!key.trim()}>Connect</Button><Button onClick={()=>{disconnect();setKey('');}} disabled={!connected}>Disconnect & forget key</Button></div></form><p className="muted small">The server access key is stored in this browser’s local storage for this site. Use this only on a trusted browser profile.</p><h3>Document encryption</h3><p>{library?.ready?'Configured and ready':library?.detail||'Unavailable until connected'}</p><h3>Appearance</h3><label>Theme<select value={theme} onChange={e=>setTheme(e.target.value)}><option value="dark">Dark</option><option value="light">Light</option><option value="system">System</option></select></label></>}
 {tab==='Personalization'&&<><h2>About you</h2><label>Name<input value={profile.name} maxLength={100} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>Background<textarea value={profile.background} maxLength={1500} onChange={e=>setProfile({...profile,background:e.target.value})}/></label><label>Preferences / default language<textarea value={profile.preferences} maxLength={1500} placeholder="I prefer Indonesian for casual conversations." onChange={e=>setProfile({...profile,preferences:e.target.value})}/></label><Button disabled={!connected} onClick={()=>void save('/profile',profile)}>Save profile</Button><h2 className="mt-6">Assistant personality</h2><label>Name<input value={identity.name} maxLength={60} onChange={e=>setIdentity({...identity,name:e.target.value})}/></label><label>Response style<textarea value={identity.personality} maxLength={1500} onChange={e=>setIdentity({...identity,personality:e.target.value})}/></label><label>Examples<textarea value={identity.response_examples} maxLength={1500} onChange={e=>setIdentity({...identity,response_examples:e.target.value})}/></label><Button disabled={!connected} onClick={()=>void save('/identity',identity)}>Save personality</Button></>}
 {tab==='Tools'&&<><h2>Tool settings</h2>{[['automatic_memory','Automatic lasting-fact memory'],['weather_enabled','Weather lookup'],['search_enabled','Web search']].map(([name,label])=><label className="check tool-setting" key={name}><input type="checkbox" checked={tools[name as keyof typeof tools]} onChange={e=>setTools({...tools,[name]:e.target.checked})}/>{label}</label>)}<p className="muted">Weather sends only the requested city to Open-Meteo. Search sends only an explicit query through the isolated lookup/search services. Page verification stays inside that egress service; inference, personal memory and files remain local.</p><Button disabled={!connected} onClick={()=>void save('/tools/settings',tools)}>Save tool settings</Button><p className="muted small">Memory records are managed from the dedicated Memory page. Live lookup services still need the live Docker profile.</p></>}
 {tab==='Runtime'&&<><div className="section-heading"><div><h2>Local model runtime</h2><p className="muted small">Select installed GGUFs without editing .env.</p></div><Button onClick={()=>void loadModels()} disabled={!connected||modelBusy}><RefreshCcw size={14}/>Refresh</Button></div>{models?<><div className="runtime-model-summary"><span>Loaded <strong className="mono">{models.loaded}</strong></span>{models.pending&&models.pending!==models.loaded&&<span>Pending <strong className="mono">{models.pending}</strong></span>}</div><label>Installed model<select value={selectedModel} onChange={e=>setSelectedModel(e.target.value)}>{models.installed.map(m=><option value={m.name} key={m.name}>{m.loaded?'● ':''}{m.name} · {m.quantization||'quant unknown'} · {(m.bytes/1024/1024/1024).toFixed(2)} GB</option>)}</select></label><Button variant="primary" onClick={()=>void stageModel()} disabled={modelBusy||!selectedModel}><ServerCog size={14}/>Stage selected model</Button><p className="muted small">Activation recreates the local LLM and backend containers; Keno never grants the web app Docker-socket access. After staging, run <code>docker compose up -d --force-recreate llm backend</code>.</p><h3>Download / install GGUF</h3><p className="muted small">Downloads use the isolated lookup egress service and accept HTTPS Hugging Face model URLs only. Start the live profile first.</p><label>Hugging Face resolve URL<input value={modelUrl} onChange={e=>setModelUrl(e.target.value)} placeholder="https://huggingface.co/.../resolve/main/model.gguf"/></label><label>Filename override (optional)<input value={modelFilename} onChange={e=>setModelFilename(e.target.value)} placeholder="model-Q4_K_M.gguf"/></label><Button onClick={()=>void downloadModel()} disabled={modelBusy||!modelUrl.trim()}><Download size={14}/>Download & install</Button><h3>Loaded runtime</h3><Json value={{model:status?.model,context_size:status?.context_size,runtime:status?.runtime}}/><h3>Recommended CPU profile</h3><Json value={models.recommendation}/></>:<p className="muted">Connect to inspect installed models.</p>}</>}
 {tab==='Lab'&&<><h2>Benchmark defaults</h2><label>Repetitions<input type="number" min={1} max={20} value={labPrefs.repetitions} onChange={e=>setLabPrefs({...labPrefs,repetitions:Math.max(1,Math.min(20,Number(e.target.value)||1))})}/></label><label>New case timeout (seconds)<input type="number" min={10} max={360} value={labPrefs.timeout} onChange={e=>setLabPrefs({...labPrefs,timeout:Math.max(10,Math.min(360,Number(e.target.value)||180))})}/></label><label>Concurrency<input type="number" value={1} disabled/></label><Button onClick={()=>{localStorage.setItem('keno.lab.preferences',JSON.stringify(labPrefs));setSaved('Harmless UI defaults saved in this browser.');}}>Save defaults</Button><h3>Exports</h3><p className="muted">Exports are explicit JSON downloads. Credential fields are stripped. Run exports may contain your prompts and answers; store downloaded files privately.</p><Button disabled={!connected} onClick={()=>{void fetch('/openapi.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('API schema unavailable');return r.json();}).then(data=>{const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='keno-openapi.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}).catch(e=>setError(e.message));}}>Download API schema</Button><details><summary>Document configuration</summary><Json value={library}/></details></>}
 {saved&&<p className="success" role="status">{saved}</p>}</section></>;
}
