import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {ApiClient,ApiError} from './api';
import type {Case,Doc,LibraryStatus,Result,Run,Runtime,Session} from './types';
interface State {api:ApiClient;connected:boolean;status:Runtime|null;sessions:Session[];runs:Run[];runTotal:number;docs:Doc[];library:LibraryStatus|null;cases:Case[];results:Result[];resultTotal:number;config:Record<string,unknown>|null;error:string;setError:(v:string)=>void;refresh:()=>Promise<void>;connect:(key:string)=>Promise<void>;disconnect:()=>void}
const Store=createContext<State|null>(null);
export const useLab=()=>{const value=useContext(Store);if(!value)throw Error('Lab provider missing');return value;};
export function LabProvider({children}:{children:ReactNode}){
 const api=useRef(new ApiClient()).current;
 const [connected,setConnected]=useState(false),[status,setStatus]=useState<Runtime|null>(null),[sessions,setSessions]=useState<Session[]>([]),[runs,setRuns]=useState<Run[]>([]),[runTotal,setRunTotal]=useState(0),[docs,setDocs]=useState<Doc[]>([]),[library,setLibrary]=useState<LibraryStatus|null>(null),[cases,setCases]=useState<Case[]>([]),[results,setResults]=useState<Result[]>([]),[resultTotal,setResultTotal]=useState(0),[config,setConfig]=useState<Record<string,unknown>|null>(null),[error,setError]=useState('');
 const generation=useRef(0),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;try{localStorage.removeItem('keno.serverAccessKey');}catch{}return()=>{mounted.current=false;};},[]);
 async function refresh(){if(!api.key)return;const ticket=generation.current;const all=await Promise.allSettled([api.get<Runtime>('/status'),api.get<Session[]>('/conversations'),api.get<{items:Run[];total:number}>('/lab/runs?limit=250'),api.get<LibraryStatus>('/library/status'),api.get<Case[]>('/lab/cases'),api.get<{items:Result[];total:number}>('/lab/results'),api.get<Record<string,unknown>>('/lab/config')]);if(ticket!==generation.current||!mounted.current)return;const [health,convos,history,vault,tests,bench,configuration]=all;if(health.status==='fulfilled'){setStatus(health.value);setConnected(true);}else{setStatus(null);setConnected(false);setError(health.reason.message);if(health.reason instanceof ApiError&&health.reason.status===401){disconnect();}return;}if(convos.status==='fulfilled')setSessions(convos.value);if(history.status==='fulfilled'){setRuns(history.value.items);setRunTotal(history.value.total);}if(vault.status==='fulfilled'){setLibrary(vault.value);if(vault.value.ready){try{const d=await api.get<Doc[]>('/library/documents');if(ticket===generation.current)setDocs(d);}catch(e){setError((e as Error).message);}}}if(tests.status==='fulfilled')setCases(tests.value);if(bench.status==='fulfilled'){setResults(bench.value.items);setResultTotal(bench.value.total);}if(configuration.status==='fulfilled')setConfig(configuration.value);for(const item of all)if(item.status==='rejected')setError(item.reason.message);}
 async function connect(key:string){generation.current++;api.key=key.trim();setError('');try{await api.get<Runtime>('/status');await refresh();}catch(e){api.key='';setConnected(false);throw e;}}
 function disconnect(){generation.current++;api.key='';setConnected(false);setStatus(null);setSessions([]);setRuns([]);setRunTotal(0);setResultTotal(0);setDocs([]);setCases([]);setResults([]);setLibrary(null);setConfig(null);setError('');}
 useEffect(()=>{if(!connected)return;const timer=setInterval(()=>{const ticket=generation.current;void api.get<Runtime>('/status').then(value=>{if(ticket===generation.current&&mounted.current)setStatus(value);}).catch(e=>{if(ticket!==generation.current||!mounted.current)return;disconnect();setError(e.message);});},10000);return()=>clearInterval(timer);},[connected]);
 return <Store.Provider value={{api,connected,status,sessions,runs,runTotal,docs,library,cases,results,resultTotal,config,error,setError,refresh,connect,disconnect}}>{children}</Store.Provider>;
}
