export interface Decision {choice:string;confidence:number|null}
export interface Route {thinking?:boolean;uncertain?:boolean;seconds?:number;question_count?:number;call_count?:number;tool_family?:string;tool_policy?:string;effort_policy?:string;decisions?:Record<string,Decision>;[key:string]:unknown}
export interface Source {attachment_id?:string;library_document_id?:string;document_id?:string;name:string;page?:number|null;chunk?:number;locator?:string;index?:number;source_id?:string;text?:string;url?:string;title?:string;[key:string]:unknown}
export interface Context {route?:Route;document_sources?:Source[];visual_sources?:Source[];web_sources?:Source[];tool_calls?:Array<{name:string;status:string;detail?:string}>;[key:string]:unknown}
export interface Run {request_id:string;conversation_id:string;user_text:string;assistant_text:string|null;status:string;created_at:string;context:Context;metadata?:string;session_title?:string}
export interface Session {id:string;title:string;created_at:string;turns?:Run[]}
export interface Doc {id:string;name:string;format:string;category:string;topic:string;version:number;passages:number;embedding_model:string|null;warnings:string[];classification:string;collection?:string;tags?:string[];metadata?:Record<string,string>;source_bytes?:number|null;section_count?:number|null;indexing_seconds?:number|null;imported_at?:string|null}
export interface Runtime {backend:string;model:string;model_ready:boolean;router:string;router_ready:boolean;generating:boolean;context_size:number;version:string;vision_enabled:boolean;[key:string]:unknown}
export interface Assertion {kind:string;value:string}
export interface Case {id:string;created_at?:string;title:string;suite:string;input:string;setup:string[];attachment_ids:string[];conversation_id?:string|null;library_document_ids?:string[];expected:string;assertions:Assertion[];timeout:number;tags:string[];intent:'fresh'|'repeat'|'followup'}
export interface Check {kind:string;passed:boolean|null;detail:string}
export interface Result {review?:{quality:number;note:string}|null;id:string;batch_id:string;case_id:string;request_id:string|null;conversation_id:string|null;status:string;checks:Check[];browser_seconds:number|null;browser_first_token_seconds:number|null;error?:string|null;repetition:number;created_at:string;configuration:Record<string,unknown>|null;case:Case|null;run:Run|null}
export interface LibraryStatus {ready:boolean;configured:boolean;detail:string|null;formats:string[];encryption:string;manual_unlock:boolean}
export interface ChatRequest {conversation_id:string;message:string;request_id:string;stream:true;max_tokens:number;execution_mode:'fast'|'balanced'|'deep';attachment_ids:string[];library_document_ids?:string[]}
export interface ChatResult {request_id:string;conversation_id:string;reply:string;context:Context}
